In [1]:
import pandas as pd
import numpy as np
import csv
import json
import datetime as dt
import random
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [2]:
# def json2csv(json_name, csv_name, key):
#     with open(json_name) as json_file:
#         data = json.load(json_file)
#     transaction_data = data[key]
#     data_file = open(csv_name, 'w') 
#     csv_writer = csv.writer(data_file)
#     count = 0
#     for tran in transaction_data:
#         if count == 0: 
#             # Writing headers of CSV file 
#             header = tran.keys()
#             csv_writer.writerow(header) 
#             count += 1
#         # Writing data of CSV file 
#         csv_writer.writerow(tran.values())
#     data_file.close() 
# json2csv('brandWise.json', 'brandWise.csv', 'data')

In [3]:
offers_df = pd.read_csv("offers.csv")
bought_df = pd.read_csv("brandWise.csv")

In [4]:
offers_df.drop(["antecedent support", "leverage", "confidence", "consequent support", "conviction", "antecedent_len", "support"],axis = 1,inplace= True)
offers_df.drop(offers_df.columns[offers_df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
bought_brands = bought_df["brand"].tolist()

In [5]:
offers_df

                      antecedents               consequents      lift
0                    Book My Show                    Zomato  1.250000
1                            Only                    Zomato  1.250000
2               Book My Show,Uber                    Zomato  1.250000
3                    Book My Show               Uber,Zomato  1.250000
4                       Only,Uber                    Zomato  1.250000
5                            Only               Uber,Zomato  1.250000
6                         Netflix                   Gilly's  1.250000
7                         iPlanet          Reliance Digital  1.666667
8                Reliance Digital                   iPlanet  1.666667
9                        HomeTown                     Croma  1.250000
10                   Shopper Stop                   Raymond  1.250000
11                        Tanishq                   Raymond  1.250000
12              Bangalore Central                Patym Mall  1.666667
13                     Patym Mall         Bangalore Central  1.666667
14              Bangalore Central                      Vans  1.250000
15                       Mi Store               Burger King  1.250000
16                 Rolls on Wheel                  Fastrack  1.250000
17                     Patym Mall                      Vans  1.250000
18         Bangalore Central,Vans                Patym Mall  1.666667
19   Bangalore Central,Patym Mall                      Vans  1.250000
20                Vans,Patym Mall         Bangalore Central  1.666667
21              Bangalore Central           Vans,Patym Mall  1.666667
22                     Patym Mall    Bangalore Central,Vans  1.666667
23                     Crossword                  Land Mark  1.250000
24                     Crossword                     Plated  1.250000
25                Sarjapur Social                 Land Mark  1.250000
26                      Meru Cabs                    Plated  1.250000
27                         Smaash                  Veremoda  1.666667
28                       Veremoda                    Smaash  1.666667
29           Land Mark,Crossword                     Plated  1.250000
30               Land Mark,Plated                Crossword   1.666667
31              Crossword ,Plated                 Land Mark  1.250000
32                     Crossword           Land Mark,Plated  1.666667
33                     Fresh Menu                    Fitbit  1.250000
34                         Fitbit                  Skechers  1.250000
35                       Skechers                    Fitbit  1.250000
36                     Fresh Menu                  Skechers  1.250000
37                        Grofers                  Spencers  1.250000
38             Eat Fit,Fresh Menu                    Fitbit  1.250000
39                     Fresh Menu            Fitbit,Eat Fit  1.250000
40                 Fitbit,Eat Fit                  Skechers  1.250000
41               Eat Fit,Skechers                    Fitbit  1.250000
42                         Fitbit          Eat Fit,Skechers  1.250000
43                       Skechers            Fitbit,Eat Fit  1.250000
44             Eat Fit,Fresh Menu                  Skechers  1.250000
45                     Fresh Menu          Eat Fit,Skechers  1.250000
46                Grofers,Eat Fit                  Spencers  1.250000
47                        Grofers          Eat Fit,Spencers  1.250000
48              Fitbit,Fresh Menu                  Skechers  1.250000
49            Fresh Menu,Skechers                    Fitbit  1.250000
50                     Fresh Menu           Fitbit,Skechers  1.250000
51                Fitbit,Spencers                  Skechers  1.250000
52              Spencers,Skechers                    Fitbit  1.250000
53              Fitbit,Fresh Menu          Eat Fit,Skechers  1.250000
54             Eat Fit,Fresh Menu           Fitbit,Skechers  1.250000
55            Fresh Menu,Skechers            Fitbit,Eat Fit  1.250000
56                     Fresh Menu   Fitbit,Eat Fit,Skechers  1.250000
57                Fitbit,Spencers          Eat Fit,Skechers  1.250000
58              Spencers,Skechers            Fitbit,Eat Fit  1.250000
59                     No Limmits                       Mac  1.666667
60                            Mac                No Limmits  1.666667
61                            Mac                    Plan B  1.250000
62                     No Limmits                    Plan B  1.250000
63              Plan B,No Limmits                       Mac  1.666667
64                     Plan B,Mac                No Limmits  1.666667
65                 No Limmits,Mac                    Plan B  1.250000
66                     No Limmits                Plan B,Mac  1.666667
67                            Mac         Plan B,No Limmits  1.666667
68                  Beijing Bites                    Ginger  1.250000
69                  Beijing Bites                Polar Bear  1.250000
70                  Beijing Bites                     Sugar  1.250000
71                     Polar Bear                    Ginger  1.250000
72                         Ginger                Polar Bear  1.250000
73       Polar Bear,Beijing Bites                    Ginger  1.250000
74           Ginger,Beijing Bites                Polar Bear  1.250000
75                  Beijing Bites         Polar Bear,Ginger  1.250000
76                   Sugar,Ginger             Beijing Bites  1.666667
77            Sugar,Beijing Bites                    Ginger  1.250000
78           Ginger,Beijing Bites                     Sugar  1.250000
79                  Beijing Bites              Sugar,Ginger  1.666667
80               Sugar,Polar Bear             Beijing Bites  1.666667
81            Sugar,Beijing Bites                Polar Bear  1.250000
82       Polar Bear,Beijing Bites                     Sugar  1.250000
83                  Beijing Bites          Sugar,Polar Bear  1.666667
84             Catwalk,Polar Bear                    Ginger  1.250000
85                 Catwalk,Ginger                Polar Bear  1.250000
86               Sugar,Polar Bear                    Ginger  1.250000
87                   Sugar,Ginger                Polar Bear  1.250000
88                    Zara,Ginger                Polar Bear  1.250000
89                Polar Bear,Zara                    Ginger  1.250000
90               Sugar,Polar Bear      Ginger,Beijing Bites  1.666667
91                   Sugar,Ginger  Polar Bear,Beijing Bites  1.666667
92            Sugar,Beijing Bites         Polar Bear,Ginger  1.250000
93       Polar Bear,Beijing Bites              Sugar,Ginger  1.666667
94           Ginger,Beijing Bites          Sugar,Polar Bear  1.666667
95                  Beijing Bites   Sugar,Polar Bear,Ginger  1.666667
96                      Ori Flame                 Fab India  1.250000
97                Inc 5,Ori Flame                 Fab India  1.250000
98                      Ori Flame           Fab India,Inc 5  1.250000
99                         Clarks                    Adidas  1.666667
100                        Adidas                    Clarks  1.666667
101                        Adidas                       Gap  1.250000
102                        Clarks                       Gap  1.250000
103                    Gap,Clarks                    Adidas  1.666667
104                    Gap,Adidas                    Clarks  1.666667
105                 Adidas,Clarks                       Gap  1.250000
106                        Clarks                Gap,Adidas  1.666667
107                        Adidas                Gap,Clarks  1.666667
108                   Allen Solly                       KFC  1.250000
109                   Allen Solly                      Sony  1.250000
110                       Hotstar                   Tatasky  1.250000
111                       Tatasky                   Hotstar  1.250000
112               Allen Solly,KFC                      Sony  1.250000
113              Allen Solly,Sony                       KFC  1.250000
114                      Sony,KFC               Allen Solly  1.666667
115                   Allen Solly                  Sony,KFC  1.666667
116                   Tatasky,KFC                   Hotstar  1.250000
117                   Hotstar,KFC                   Tatasky  1.250000
118                  Sony,Hotstar                   Tatasky  1.250000
119                  Sony,Tatasky                   Hotstar  1.250000

In [6]:
print(type(offers_df.at[0,"antecedents"]))

<class 'str'>

In [13]:
to_rec = []
for i in range(offers_df.shape[0]):
    a = offers_df.at[i,"antecedents"].split(',')
    b = offers_df.at[i,"consequents"].split(',')
    #print (a,b)
    for i in a:
        print((i).strip())
        if i in bought_brands:
            print("yes")
            for j in b:
                to_rec.append(j)

Book My Show
Only
yes
Book My Show
Uber
yes
Book My Show
Only
yes
Uber
yes
Only
yes
Netflix
yes
iPlanet
yes
Reliance Digital
HomeTown
Shopper Stop
Tanishq
Bangalore Central
yes
Patym Mall
Bangalore Central
yes
Mi Store
Rolls on Wheel
Patym Mall
Bangalore Central
yes
Vans
Bangalore Central
yes
Patym Mall
Vans
Patym Mall
Bangalore Central
yes
Patym Mall
Crossword
Crossword
Sarjapur Social
Meru Cabs
Smaash
Veremoda
Land Mark
yes
Crossword
Land Mark
yes
Plated
yes
Crossword
Plated
yes
Crossword
Fresh Menu
Fitbit
Skechers
Fresh Menu
Grofers
Eat Fit
yes
Fresh Menu
Fresh Menu
Fitbit
Eat Fit
yes
Eat Fit
yes
Skechers
Fitbit
Skechers
Eat Fit
yes
Fresh Menu
Fresh Menu
Grofers
Eat Fit
yes
Grofers
Fitbit
Fresh Menu
Fresh Menu
Skechers
Fresh Menu
Fitbit
Spencers
yes
Spencers
yes
Skechers
Fitbit
Fresh Menu
Eat Fit
yes
Fresh Menu
Fresh Menu
Skechers
Fresh Menu
Fitbit
Spencers
yes
Spencers
yes
Skechers
No Limmits
yes
Mac
Mac
No Limmits
yes
Plan B
No Limmits
yes
Plan B
Mac
No Limmits
yes
Mac
No Limmits
yes
Mac
Beijing Bites
yes
Beijing Bites
yes
Beijing Bites
yes
Polar Bear
Ginger
Polar Bear
Beijing Bites
yes
Ginger
Beijing Bites
yes
Beijing Bites
yes
Sugar
yes
Ginger
Sugar
yes
Beijing Bites
yes
Ginger
Beijing Bites
yes
Beijing Bites
yes
Sugar
yes
Polar Bear
Sugar
yes
Beijing Bites
yes
Polar Bear
Beijing Bites
yes
Beijing Bites
yes
Catwalk
yes
Polar Bear
Catwalk
yes
Ginger
Sugar
yes
Polar Bear
Sugar
yes
Ginger
Zara
Ginger
Polar Bear
Zara
Sugar
yes
Polar Bear
Sugar
yes
Ginger
Sugar
yes
Beijing Bites
yes
Polar Bear
Beijing Bites
yes
Ginger
Beijing Bites
yes
Beijing Bites
yes
Ori Flame
yes
Inc 5
Ori Flame
yes
Ori Flame
yes
Clarks
Adidas
yes
Adidas
yes
Clarks
Gap
Clarks
Gap
Adidas
yes
Adidas
yes
Clarks
Clarks
Adidas
yes
Allen Solly
Allen Solly
Hotstar
Tatasky
Allen Solly
KFC
yes
Allen Solly
Sony
Sony
KFC
yes
Allen Solly
Tatasky
KFC
yes
Hotstar
KFC
yes
Sony
Hotstar
Sony
Tatasky

In [16]:
to_rec = set(to_rec)

In [35]:
results = []
for i in to_rec:
    if i not in bought_brands:
        results.append(i)

In [36]:
results

['Fab India',
 'Vans',
 'Skechers',
 'Reliance Digital',
 'Fitbit',
 'Gap',
 'Polar Bear',
 'Patym Mall',
 'Ginger',
 'Mac',
 'Crossword ',
 'Sony',
 'Plan B',
 'Hotstar',
 'Allen Solly',
 'Tatasky',
 'Inc 5',
 'Clarks']

In [37]:
results.remove('Allen Solly')
results.remove('Clarks')
results.remove('Tatasky')
results.remove('Patym Mall')
results.remove('Ginger')
results.remove('Fab India')

In [39]:
(results)

['Vans',
 'Skechers',
 'Reliance Digital',
 'Fitbit',
 'Gap',
 'Polar Bear',
 'Mac',
 'Crossword ',
 'Sony',
 'Plan B',
 'Hotstar',
 'Inc 5']

In [40]:
bought_df

                 brand  amount
0              iPlanet   89000
1           Clear Trip   34602
2           Indian Oil   22029
3             Spencers   21903
4               Adidas   17499
5              Gilly's   16499
6                  H&M   15987
7        Amazon (AMZN)   15644
8           No Limmits   15071
9            Veromoda    13672
10             Netflix    9588
11   Bangalore Central    8502
12           Land Mark    8188
13      Titan Eye Plus    7999
14                Uber    5925
15                 KFC    5408
16     Kwality Bazaar     5286
17  American Tourister    4999
18                 PVR    4722
19       Beijing Bites    4308
20             Tonique    3500
21                Amul    3300
22          Big Basket    2736
23              BBlunt    2598
24              Plated    2110
25                Only    2100
26           Ori Flame    2019
27           Decathlon    2001
28             Catwalk    1999
29              Zomato    1757
30             Eat Fit    1556
31              Myntra    1400
32                Bluo    1400
33            Sky Bags    1299
34               Sugar    1240
35               IRCTC     789
36         Smoke House     743
37         Burger King     726
38          Mr Goofy's     670
39               Croma     599
40       Stoned Monkey     480
41          Chai Point     419
42           Hairspeak     399
43                 A2B     310
44              Swiggy     270
45          Leon Grill     242
46            SK Rolls      80

In [41]:
loyalty_brands = ['iPlanet', 'Adidas', "Gilly's", "H&M", "PVR", "KFC", "BBlunt", "Amul"]

In [42]:
loyaly_df = pd.DataFrame({"brand":loyalty_brands})
rec_df = pd.DataFrame({"brand":results})

In [43]:
loyaly_df

     brand
0  iPlanet
1   Adidas
2  Gilly's
3      H&M
4      PVR
5      KFC
6   BBlunt
7     Amul

In [45]:
rec_df

               brand
0               Vans
1           Skechers
2   Reliance Digital
3             Fitbit
4                Gap
5         Polar Bear
6                Mac
7         Crossword
8               Sony
9             Plan B
10           Hotstar
11             Inc 5

In [47]:
loyaly_df.to_json("loyalty.json",orient = "records")
rec_df.to_json("rec.json",orient = "records")